### ISSUE TITLE
Fails when testing via Jest

### ISSUE THREAD

**Issue by Moe-kanan** [segmentio/sovran-react-native#42]
Hello, our tests are failing with the below error! 
Not sure if this is a known issue in `sovern-react-native` or am I doing something wrong? Please help! thanks!

Initially, the tests were failing on async-storage
```
● Test suite failed to run

    [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
```

But after mocking `react-native-async-storage`, now it's failing with this

```
  ● Test suite failed to run

    The package 'sovran-react-native' doesn't seem to be linked. Make sure: 

    - You have run 'pod install'
    - You rebuilt the app after installing the package
    - You are not using Expo managed workflow

      at Object.getConstants [as get] (node_modules/@segment/sovran-react-native/lib/commonjs/index.tsx:16:17)
      at Object.<anonymous> (node_modules/@segment/sovran-react-native/lib/commonjs/index.tsx:21:36)
      at Object.<anonymous> (node_modules/@segment/analytics-react-native/lib/commonjs/plugins/QueueFlushingPlugin.ts:1:1)
```

in package.json
```
"@segment/analytics-react-native": "^2.7.1"
"@segment/analytics-react-native-plugin-braze": "^0.4.0"
"react-native": "0.64.3"
"expo": "^44.0.0"
"jest-expo": "^44.0.0"
```

**Comment by jonwagner** [comment]
Further analysis in this library's index.js, it appears to expect one of the native libraries to be loaded (iOS/android). However, in the test scenarios, there are no native libraries to load.

```
const LINKING_ERROR = `The package 'sovran-react-native' doesn't seem to be linked. Make sure: \n\n` + _reactNative.Platform.select({
  ios: "- You have run 'pod install'\n",
  default: ''
}) + '- You rebuilt the app after installing the package\n' + '- You are not using Expo managed workflow\n';
const Sovran = _reactNative.NativeModules.Sovran ? _reactNative.NativeModules.Sovran : new Proxy({}, {
  get() {
    throw new Error(LINKING_ERROR);
  }

});
```

**Comment by jonwagner** [comment]
We are able to run our test suite if we fully mock out the following:

```
jest.mock('@segment/analytics-react-native', () => {
});
jest.mock('@segment/analytics-react-native-plugin-braze', () => {
});
jest.mock('react-native-appboy-sdk', () => {
});
```

are there off-the-shelf library mocks for these so we don't have to manually write the mock code?

**Comment by gregg062** [comment]
I was able to fix the issue by adding:

```
jest.mock('@segment/analytics-react-native', () => {
  return {
    createClient: jest.fn(),
  }
})
```

**Comment by jonwagner** [comment]
worth updating the code but you can close this

**Comment by scaraux** [comment]
```
  jest.mock('@segment/analytics-react-native-plugin-braze', () => {});
  jest.mock('@segment/analytics-react-native-plugin-firebase', () => {});
  jest.mock('@segment/analytics-react-native', () => {
    return {
      useAnalytics: jest.fn(),
      createClient: jest.fn()
      }),
    };
  });
```

did the trick. note you probably don't need to mock trac
